language: java

sudo: false

before-script:
 - cd webapp/
 - npm test && npm run build

script:
  - mvn validate clean install | grep -v "(^\[ERROR\])"
cache:
  directories:
  - "$HOME/.m2"

jdk:
  - oraclejdk8

before-install:
  - cd webapp/

install:
  - npm install 	
