language: java

sudo: false

node_js:
  - "8"
  - "6"

cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.yarn-cache"

jdk:
  - oraclejdk8

before_script:
    - export TZ=Poland

jobs:
  include:
    - stage: clean repo & prepare depedency
      script: bash ./scripts/prepare.sh
    - stage: unit tests - backend
      script: bash ./scripts/unit-tests-bk.sh
    - stage: integration tests - backend
      script: bash ./scripts/int-tests-bk.sh
      after_success: bash <(curl -s https://codecov.io/bash)
      after_failure: bash <(curl -s https://codecov.io/bash)
    - stage: build docker images
      script: bash ./scripts/docker.sh


notifications:
  email: false
  slack:
    rooms:
      - books-sharing:0EAfyNQ5bGvqZSLvdFInnbs1#ci
