language: java

sudo: false

node_js:
  - "8"
  - "6"

before_script:
  - cd nb-frotend/
  - yarn build

script:
  - cd ..
  - cd nb-backend/
  - mvn clean test -q -Dlog4j.configurationFile=null
  - mvn cobertura:cobertura-integration-test -q -Dlog4j.configurationFile=null
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.yarn-cache"

jdk:
  - oraclejdk8

before_install:
   - export TZ=Poland
   - npm install -g yarn
   - yarn add global ng
   - yarn add global codecov

install:
  - yarn install --check-files --cwd nb-frontend\
#  todo write proper configuration for frontend

notifications:
  email: false
  slack:
    rooms:
      - books-sharing:0EAfyNQ5bGvqZSLvdFInnbs1#ci

after_success:
  - mvn verify -DskipTests=true
  - cp -fr nb-frontend/build/ nb-backend/src/main/webapp/WEB-INF/static/
  - bash <(curl -s https://codecov.io/bash)

after_failure:
  - bash <(curl -s https://codecov.io/bash)
