language: java

sudo: false

node_js:
  - "8"

script:
  - mvn clean install -Dlog4j.configurationFile=null
  - mvn cobertura:cobertura -Dlog4j.configurationFile=null

cache:
  directories:
  - "$HOME/.m2"

jdk:
  - oraclejdk8

before_install:
    - export TZ=Poland

install:
  - npm install --prefix src/main/webapp/

notifications:
  email: false

after_success:
  - bash <(curl -s https://codecov.io/bash)

after_failure:
  - bash <(curl -s https://codecov.io/bash)
