language: java

sudo: false

script:
  mvn validate clean install -X | egrep -v "(^\[DEBUG\])"
cache:
  directories:
  - "$HOME/.m2"

jdk:
  - oraclejdk8

before-install:
  - cd webapp/

install:
  - npm install 	
