language: java

sudo: required

node_js:
  - "8"

cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.yarn-cache"

jdk:
  - oraclejdk8

before_script:
    - export TZ=Poland
    - chmod +x travis.sh

jobs:
  include:
    - stage: unit tests - backend
      script: ./travis.sh bk_unit_test
    - stage: integration tests - backend
      script: ./travis.sh bk_integration_test
      after_success: bash <(curl -s https://codecov.io/bash)
      after_failure: bash <(curl -s https://codecov.io/bash)
    - stage: build services & docker images
      script: ./travis.sh build_services_with_docker

notifications:
  email: false
  slack:
    rooms:
      - books-sharing:0EAfyNQ5bGvqZSLvdFInnbs1#ci
