language: java

sudo: false

node_js:
  - "8"

before_script:
 - npm test --coverage --prefix src/main/webapp/  
 - npm run build --prefix src/main/webapp/

script:
  mvn validate clean install | egrep -v "(^\[INFO\]|^\[DEBUG\]^\INFO\)"
cache:
  directories:
  - "$HOME/.m2"

jdk:
  - oraclejdk8

install:
  - cd src/main/webapp/
  - npm install 	
