language: java

sudo: false

script:
  - mvn clean install -q -DtrimStackTrace=false 

cache:
  directories:
  - "$HOME/.m2"

jdk:
  - oraclejdk8

before-install:
  - cd src/main/webapp/

install:
  - npm install 	
