language: java

sudo: false

node_js:
  - "8"

script:
  mvn clean test -q -Dlog4j.configurationFile=null | egrep -v "(^\[INFO\]|^\[DEBUG\])"

cache:
  directories:
  - "$HOME/.m2"

jdk:
  - oraclejdk8

install:
  - npm install --prefix src/main/webapp/

notifications:
  email: false

