language: java

sudo: false

before_script:
 - npm test && npm run build

script:
  mvn validate clean install | egrep -v "(^\[INFO\]|^\[DEBUG\]^\INFO\)"
cache:
  directories:
  - "$HOME/.m2"

jdk:
  - oraclejdk8

install:
  - npm install 	
